Cars/urls.py
from django.contrib import admin
from django.urls import path, include
from Cars import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars_filter.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cars_filter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cars_filter'

urlpatterns = [
    path('', views.CarsView.as_view(), name='index'),
    # path('search/', views.SearchCarView.as_view(), name='search'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars_filter/models.py
from django.db import models

# Create your models here.
class Car(models.Model):

    TRANSMISSION = [
        (1, 'Механика'),
        (2, 'Автомат'),
        (3, 'Робот'),
    ]
    COLOR = [
        (1, 'Черный'),
        (2, 'Красный'),
        (3, 'Белый'),
        (4, 'Мокрый асфальт'),
        (5, 'Желтый'),
    ]

    creater = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year_create = models.IntegerField()
    transmission = models.SmallIntegerField(choices=TRANSMISSION)
    color = models.SmallIntegerField(choices=COLOR)
    photo = models.ImageField(upload_to='cars_photo/', blank=True,)


    def __str__(self):
        a = str('{} - {} - {}'.format(self.creater, self.model, self.year_create))
        return a

cars_filter/views.py
from django.shortcuts import render
from cars_filter import models
from django.views.generic.list import ListView
from django.db.models import Q


# Create your views here.

class CarsView(ListView):
    model = models.Car
    template_name = 'cars_filter/index.html'


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = models.Car.objects.order_by().values_list('creater').distinct()
        context['models'] = models.Car.objects.order_by().values_list('model').distinct()
        context['transmission'] = models.Car.objects.order_by().values_list('transmission').distinct()
        context['colors'] = models.Car.objects.order_by().values_list('color').distinct()
        context['year_create'] = models.Car.objects.order_by().values_list('year_create').distinct()
        return context

    def get_queryset(self):
        if self.request.GET:
            get_query = Q()
            request_get = {}

            request_get['creater'] = self.request.GET.getlist('creater[]', None)
            request_get['model'] = self.request.GET.getlist('model[]', None)
            request_get['transmission'] = self.request.GET.getlist('transmission[]', None)
            request_get['color'] = self.request.GET.getlist('color[]', None)
            request_get['year_create'] = self.request.GET.getlist('year_create[]', None)

            for key, value in request_get.items():
                category = Q()
                print(key)
                for a in value:
                    category |= Q(**{key: a})
                get_query &= category
                print(get_query)

            return models.Car.objects.filter(get_query)

        else:
            return models.Car.objects.all()

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Авто подбор</title>
</head>
<body>
    <div class="container">
        <div class="header mb-3">
            <h1 class="h1 mb-3">Поиск автомобилей по параметрам</h1>
            <a href="/">Показать все автомобили</a>
        </div>
        <div class="form-row">
            {% block search %}
            {% endblock %}
        </div>
        <div class="d-flex flex-row flex-wrap">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/cars_filter/index.html
{% extends 'base.html' %}

{% block search %}
    {% include "cars_filter/search_block.html" %}
{% endblock %}


{% block content %}
    {% for car in object_list %}
    <div class="card m-3" style="width: 30%;">
        <img class="card-img-top p-2" style="width: 100%; height: 220px" src="{{ car.photo.url }}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ car.creater }} {{ car.model }} ({{ car.year_create }})</h5>
            <p class="card-text"> <span class="h6"> Коробка передач: </span> {{ car.get_transmission_display }}</p>
            <p class="card-text"> <span class="h6"> Цвет: </span>{{ car.get_color_display }}</p>
        </div>
    </div>
    {% empty %}
        <h5 class="h5 mt-3">По данным параметрам автомобили не найдены. Попробуйте изменить параметры поиска.</h5>
    {% endfor %}
{% endblock %}

templates/cars_filter/search_block.html
    <form class="d-flex flex-column" method = 'GET' action="/">
    {% csrf_token %}
        <div class="mb-3">
            <h5 class="h5">Марка автомобиля</h5>

            <div class="form-check form-check-inline">
                {% for car in cars %}
                <input class="form-check-input mr-3" name = 'creater[]' type="checkbox" id="inlineCheckbox1" value="{{ car.0 }}">
                <label class="form-check-label mr-3" for="inlineCheckbox1">{{ car.0 }}</label>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <h5 class="h5">Модель автомобиля</h5>

            <div class="form-check form-check-inline">
                {% for model in models %}
                <input class="form-check-input mr-3" name = 'model[]' type="checkbox" id="inlineCheckbox1" value="{{ model.0 }}">
                <label class="form-check-label mr-3" for="inlineCheckbox1">{{ model.0 }}</label>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3 d-flex flex-row">
            <h5 class="h5 mr-3">Коробка передач</h5>
            <div class="form-check form-check-inline">
                {% for type in transmission %}
                <input class="form-check-input mr-3" name = 'transmission[]' type="checkbox" id="inlineCheckbox1" value="{{ type.0 }}">
                <label class="form-check-label mr-3" for="inlineCheckbox1">
                    {% if type.0 == 1 %}
                        Механика
                    {% elif type.0 == 2 %}
                        Автомат
                    {% else %}
                        Робот
                    {% endif %}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3 d-flex flex-row">
            <h5 class="h5 mr-3">Год выпуска</h5>
            <div class="form-check form-check-inline">
                {% for year in year_create %}
                <input class="form-check-input mr-3" name = 'year_create[]' type="checkbox" id="inlineCheckbox1" value="{{ year.0 }}">
                <label class="form-check-label mr-3" for="inlineCheckbox1">{{ year.0 }}</label>
                {% endfor %}
            </div>
        </div>
    <div class="mb-3 d-flex flex-row">
            <h5 class="h5 mr-3">Цвет кузова</h5>
            <div class="form-check form-check-inline">
                {% for color in colors %}
                <input class="form-check-input mr-3" name = 'color[]' type="checkbox" id="inlineCheckbox1" value="{{ color.0 }}">
                <label class="form-check-label mr-3" for="inlineCheckbox1">
                    {% if color.0 == 1 %}
                        Черный
                    {% elif color.0 == 2 %}
                        Красный
                    {% elif color.0 == 3 %}
                        Белый
                    {% elif color.0 == 4 %}
                        Мокрый асфальт
                    {% else %}
                        Желтый
                    {% endif %}
                </label>
                {% endfor %}
            </div>
        </div>

        <button class="btn btn-success mb-3" type="submit" style="width: 200px">Поиск</button>

    </form>